import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";

const root = resolve(".");

function countTsx(dir) {
  try {
    return readdirSync(join(root, dir)).filter((f) => f.endsWith(".tsx")).length;
  } catch {
    return 0;
  }
}

function countThemeTokens(cssPath) {
  const text = readFileSync(cssPath, "utf8");
  const themeMatch = text.match(/@theme\s*\{([\s\S]*?)\n\}/);
  if (!themeMatch) return 0;
  const theme = themeMatch[1];
  let inside = false;
  let count = 0;
  for (const line of theme.split("\n")) {
    if (line.includes("@keyframes")) { inside = true; continue; }
    if (inside && line.trim() === "}") { inside = false; continue; }
    if (!inside && /^\s+--/.test(line)) count++;
  }
  return count;
}

const atoms     = countTsx("src/components/atoms");
const molecules = countTsx("src/components/molecules");
const organisms = countTsx("src/components/organisms");
const templates = countTsx("src/components/templates");
const ui        = countTsx("src/components/ui");
const rawTokens = countThemeTokens("src/index.css");
const tokenFloor = `${Math.floor(rawTokens / 10) * 10}+`;

mkdirSync(join(root, "src/generated"), { recursive: true });

const out = `// Auto-generated by scripts/generate-counts.mjs — do not edit by hand
export const ATOMS     = "${atoms}";
export const MOLECULES = "${molecules}";
export const ORGANISMS = "${organisms}";
export const TEMPLATES = "${templates}";
export const UI        = "${ui}";
export const TOKENS    = "${tokenFloor}";
`;

writeFileSync(join(root, "src/generated/counts.ts"), out);
console.log(`✓ counts.ts — atoms:${atoms} molecules:${molecules} organisms:${organisms} templates:${templates} ui:${ui} tokens:${tokenFloor}`);
